/**
 * Comprehensive Curated Nagpur Points of Interest (POIs), Landmarks,
 * Malls, Colleges, Hospitals, Resorts, Lakes, and Major Localities.
 */

export interface NagpurPOI {
  id: string;
  name: string;
  category: "Mall" | "Resort" | "Lake" | "College" | "Hospital" | "Temple" | "Monument" | "Transit" | "Locality";
  subtitle: string;
  lat: number;
  lon: number;
  keywords: string[];
}

export const NAGPUR_POIS: NagpurPOI[] = [
  // ─── RESORTS & LEISURE ───
  {
    id: "poi_dream_valley",
    name: "Dream Valley Resort",
    category: "Resort",
    subtitle: "Digdoh, Hingna, Nagpur",
    lat: 21.1006,
    lon: 78.9903,
    keywords: ["dream", "valley", "resort", "hingna", "digdoh", "waterpark", "picnic"],
  },
  {
    id: "poi_fun_n_food",
    name: "Fun N Food Village Water Park",
    category: "Resort",
    subtitle: "Amravati Road, Bazargaon, Nagpur",
    lat: 21.1512,
    lon: 78.7845,
    keywords: ["fun", "food", "village", "water", "park", "amravati", "road"],
  },
  {
    id: "poi_krazy_castle",
    name: "Krazy Castle Aqua Park",
    category: "Resort",
    subtitle: "Opp. Ambazari Lake, North Ambazari Road",
    lat: 21.1292,
    lon: 79.0438,
    keywords: ["krazy", "castle", "aqua", "park", "ambazari"],
  },
  {
    id: "poi_highland_waterfront",
    name: "Highland Waterfront",
    category: "Resort",
    subtitle: "Near Gorewada Lake, Katol Road, Nagpur",
    lat: 21.1965,
    lon: 79.0345,
    keywords: ["highland", "waterfront", "gorewada", "lake", "resort"],
  },

  // ─── MALLS & SHOPPING ───
  {
    id: "poi_vr_mall",
    name: "VR Nagpur Mall (Trillium Mall)",
    category: "Mall",
    subtitle: "Medical Square, Untkhana, Nagpur",
    lat: 21.1288,
    lon: 79.0985,
    keywords: ["vr", "mall", "trillium", "medical", "square", "untkhana", "shopping", "cinema"],
  },
  {
    id: "poi_empress_mall",
    name: "Empress City Mall",
    category: "Mall",
    subtitle: "Near Gandhi Sagar Lake, Cotton Market, Nagpur",
    lat: 21.1448,
    lon: 79.0945,
    keywords: ["empress", "city", "mall", "gandhi", "sagar", "cotton", "market"],
  },
  {
    id: "poi_eternity_mall",
    name: "Eternity Mall",
    category: "Mall",
    subtitle: "Variety Square, Sitabuldi, Nagpur",
    lat: 21.1432,
    lon: 79.0782,
    keywords: ["eternity", "mall", "variety", "square", "sitabuldi", "inox"],
  },
  {
    id: "poi_fortune_mall",
    name: "Fortune Mall",
    category: "Mall",
    subtitle: "Sitabuldi, Nagpur",
    lat: 21.1425,
    lon: 79.0815,
    keywords: ["fortune", "mall", "sitabuldi"],
  },
  {
    id: "poi_jaswant_tuli_mall",
    name: "Jaswant Tuli Mall",
    category: "Mall",
    subtitle: "Indora Chowk, Kamptee Road, Nagpur",
    lat: 21.1735,
    lon: 79.1022,
    keywords: ["jaswant", "tuli", "mall", "indora", "kamptee", "road"],
  },
  {
    id: "poi_dharampeth_shopping",
    name: "Dharampeth Shopping Market",
    category: "Mall",
    subtitle: "West High Court (WHC) Road, Dharampeth",
    lat: 21.1418,
    lon: 79.0601,
    keywords: ["dharampeth", "market", "whc", "road", "shopping", "clothes", "jewelry"],
  },
  {
    id: "poi_sadar_bazaar",
    name: "Sadar Residency Market",
    category: "Mall",
    subtitle: "Residency Road, Sadar, Nagpur",
    lat: 21.1610,
    lon: 79.0820,
    keywords: ["sadar", "bazaar", "residency", "road", "haldiram"],
  },
  {
    id: "poi_itwari_market",
    name: "Itwari Wholesale Market",
    category: "Mall",
    subtitle: "Itwari, Central Nagpur",
    lat: 21.1535,
    lon: 79.1125,
    keywords: ["itwari", "market", "cloth", "grain", "sarafa"],
  },

  // ─── LAKES & PARKS ───
  {
    id: "poi_futala_lake",
    name: "Futala Lake Waterfront & Promenade",
    category: "Lake",
    subtitle: "Bharat Nagar, West Nagpur",
    lat: 21.1542,
    lon: 79.0435,
    keywords: ["futala", "lake", "waterfront", "promenade", "fountain", "sunset"],
  },
  {
    id: "poi_ambazari_lake",
    name: "Ambazari Lake & Garden",
    category: "Lake",
    subtitle: "Ambazari, South-West Nagpur",
    lat: 21.1275,
    lon: 79.0390,
    keywords: ["ambazari", "lake", "garden", "boating"],
  },
  {
    id: "poi_gorewada_zoo",
    name: "Balasaheb Thackeray Gorewada International Zoo & Lake",
    category: "Lake",
    subtitle: "Katol Road, Gorewada, Nagpur",
    lat: 21.1985,
    lon: 79.0420,
    keywords: ["gorewada", "lake", "zoo", "safari", "jungle", "katol"],
  },
  {
    id: "poi_gandhisagar_lake",
    name: "Gandhisagar Lake (Shukrawari Talao)",
    category: "Lake",
    subtitle: "Raman Science Centre, Mahal, Nagpur",
    lat: 21.1440,
    lon: 79.0980,
    keywords: ["gandhisagar", "shukrawari", "talao", "lake", "raman", "science"],
  },
  {
    id: "poi_japanese_garden",
    name: "Japanese Rose Garden & Seminary Hills",
    category: "Lake",
    subtitle: "Seminary Hills, Civil Lines, Nagpur",
    lat: 21.1685,
    lon: 79.0610,
    keywords: ["japanese", "garden", "seminary", "hills", "rose"],
  },
  {
    id: "poi_botanical_garden",
    name: "PKV Botanical Garden",
    category: "Lake",
    subtitle: "Near Maharajbagh, Bajaj Nagar Road, Nagpur",
    lat: 21.1390,
    lon: 79.0685,
    keywords: ["botanical", "garden", "pkv", "maharajbagh"],
  },

  // ─── COLLEGES & UNIVERSITIES ───
  {
    id: "poi_vnit",
    name: "VNIT (Visvesvaraya National Institute of Tech)",
    category: "College",
    subtitle: "South Ambazari Road, Bajaj Nagar, Nagpur",
    lat: 21.1245,
    lon: 79.0520,
    keywords: ["vnit", "visvesvaraya", "national", "institute", "technology", "engineering", "bajaj", "nagar"],
  },
  {
    id: "poi_aiims_nagpur",
    name: "AIIMS Nagpur",
    category: "College",
    subtitle: "Sector 20, MIHAN, Nagpur",
    lat: 21.0365,
    lon: 79.0290,
    keywords: ["aiims", "all", "india", "medical", "hospital", "mihan"],
  },
  {
    id: "poi_iim_nagpur",
    name: "IIM Nagpur",
    category: "College",
    subtitle: "MIHAN, Non-SEZ Area, Nagpur",
    lat: 21.0395,
    lon: 79.0340,
    keywords: ["iim", "management", "institute", "mihan"],
  },
  {
    id: "poi_iiit_nagpur",
    name: "IIIT Nagpur",
    category: "College",
    subtitle: "Behind BSNL Regional Training, Butibori, Nagpur",
    lat: 20.9515,
    lon: 79.0310,
    keywords: ["iiit", "information", "technology", "butibori"],
  },
  {
    id: "poi_gmc_nagpur",
    name: "GMC (Government Medical College & Hospital)",
    category: "College",
    subtitle: "Medical Square, Hanuman Nagar, Nagpur",
    lat: 21.1320,
    lon: 79.0965,
    keywords: ["gmc", "government", "medical", "college", "hospital", "hanuman", "nagar"],
  },
  {
    id: "poi_rcoem",
    name: "Ramdeobaba University (RCOEM)",
    category: "College",
    subtitle: "Katol Road, Gittikhadan, Nagpur",
    lat: 21.1765,
    lon: 79.0605,
    keywords: ["rcoem", "ramdeobaba", "college", "engineering", "university", "katol", "road"],
  },
  {
    id: "poi_ycce",
    name: "YCCE (Yeshwantrao Chavan College of Engineering)",
    category: "College",
    subtitle: "Wanadongri, Hingna Road, Nagpur",
    lat: 21.0965,
    lon: 78.9790,
    keywords: ["ycce", "yeshwantrao", "chavan", "engineering", "wanadongri", "hingna"],
  },
  {
    id: "poi_raisoni",
    name: "G H Raisoni College of Engineering",
    category: "College",
    subtitle: "CRPF Gate No. 3, Digdoh Hills, Hingna Road",
    lat: 21.1015,
    lon: 78.9865,
    keywords: ["raisoni", "gh", "college", "engineering", "digdoh", "crpf", "hingna"],
  },
  {
    id: "poi_lit",
    name: "Laxminarayan Innovation Tech University (LIT)",
    category: "College",
    subtitle: "Amravati Road, Ram Nagar, Nagpur",
    lat: 21.1475,
    lon: 79.0495,
    keywords: ["lit", "laxminarayan", "technology", "amravati", "road"],
  },
  {
    id: "poi_dharampeth_college",
    name: "Dharampeth Science College",
    category: "College",
    subtitle: "Ambazari Road, Dharampeth, Nagpur",
    lat: 21.1395,
    lon: 79.0558,
    keywords: ["dharampeth", "science", "college"],
  },
  {
    id: "poi_lad_college",
    name: "L.A.D. College for Women",
    category: "College",
    subtitle: "Shankar Nagar Square, Nagpur",
    lat: 21.1370,
    lon: 79.0620,
    keywords: ["lad", "college", "women", "shankar", "nagar"],
  },
  {
    id: "poi_hislop_college",
    name: "Hislop College",
    category: "College",
    subtitle: "Temple Road, Civil Lines, Nagpur",
    lat: 21.1510,
    lon: 79.0735,
    keywords: ["hislop", "college", "civil", "lines"],
  },

  // ─── HOSPITALS ───
  {
    id: "poi_kingsway_hospital",
    name: "Kingsway Hospitals",
    category: "Hospital",
    subtitle: "Near Nagpur Railway Station, Mohan Nagar",
    lat: 21.1555,
    lon: 79.0865,
    keywords: ["kingsway", "hospital", "railway", "station", "mohan", "nagar"],
  },
  {
    id: "poi_max_hospital",
    name: "Max Super Speciality Hospital (Alexis)",
    category: "Hospital",
    subtitle: "Mankapur, Koradi Road, Nagpur",
    lat: 21.1895,
    lon: 79.0810,
    keywords: ["max", "alexis", "hospital", "mankapur", "koradi", "road"],
  },
  {
    id: "poi_care_hospital",
    name: "Care Hospital",
    category: "Hospital",
    subtitle: "Panchsheel Square, Wardha Road, Ramdaspeth",
    lat: 21.1380,
    lon: 79.0790,
    keywords: ["care", "hospital", "panchsheel", "square", "wardha", "road", "ramdaspeth"],
  },
  {
    id: "poi_wockhardt_hospital",
    name: "Wockhardt Super Speciality Hospital",
    category: "Hospital",
    subtitle: "1643, North Ambazari Road, Shankar Nagar",
    lat: 21.1355,
    lon: 79.0625,
    keywords: ["wockhardt", "hospital", "ambazari", "shankar", "nagar"],
  },
  {
    id: "poi_orange_city_hospital",
    name: "Orange City Hospital & Research Institute",
    category: "Hospital",
    subtitle: "Khamla Square, Ring Road, Nagpur",
    lat: 21.1120,
    lon: 79.0620,
    keywords: ["orange", "city", "hospital", "khamla", "square", "ring", "road"],
  },

  // ─── MONUMENTS & TEMPLES ───
  {
    id: "poi_deekshabhoomi",
    name: "Deekshabhoomi Stupa",
    category: "Monument",
    subtitle: "South Ambazari Road, Shraddhanand Peth",
    lat: 21.1275,
    lon: 79.0665,
    keywords: ["deekshabhoomi", "stupa", "buddhist", "ambedkar", "shraddhanand", "peth"],
  },
  {
    id: "poi_dragon_palace",
    name: "Dragon Palace Buddhist Temple",
    category: "Temple",
    subtitle: "Kamptee, North Nagpur",
    lat: 21.2260,
    lon: 79.1985,
    keywords: ["dragon", "palace", "temple", "kamptee", "buddhist", "lotus"],
  },
  {
    id: "poi_koradi_temple",
    name: "Shree Mahalaxmi Jagdamba Temple (Koradi)",
    category: "Temple",
    subtitle: "Koradi, Chhindwara Road, Nagpur",
    lat: 21.2465,
    lon: 79.0970,
    keywords: ["koradi", "temple", "mahalaxmi", "jagdamba", "chhindwara", "road"],
  },
  {
    id: "poi_tekdi_ganesh",
    name: "Shri Ganesh Mandir Tekdi",
    category: "Temple",
    subtitle: "Station Road, Sitabuldi, Nagpur",
    lat: 21.1505,
    lon: 79.0870,
    keywords: ["tekdi", "ganesh", "mandir", "temple", "railway", "station", "sitabuldi"],
  },
  {
    id: "poi_swaminarayan_temple",
    name: "BAPS Shri Swaminarayan Mandir",
    category: "Temple",
    subtitle: "Middle Ring Road, Wathoda Layout, Nagpur",
    lat: 21.1420,
    lon: 79.1510,
    keywords: ["swaminarayan", "mandir", "temple", "baps", "wathoda", "ring", "road"],
  },
  {
    id: "poi_sitabuldi_fort",
    name: "Sitabuldi Fort",
    category: "Monument",
    subtitle: "Sitabuldi Hill, Central Nagpur",
    lat: 21.1470,
    lon: 79.0835,
    keywords: ["sitabuldi", "fort", "military", "british", "hill"],
  },
  {
    id: "poi_zero_mile",
    name: "Zero Mile Stone Monument",
    category: "Monument",
    subtitle: "Wardha Road / Civil Lines, Nagpur",
    lat: 21.1478,
    lon: 79.0805,
    keywords: ["zero", "mile", "stone", "centre", "india", "monument"],
  },

  // ─── TRANSIT HUBS ───
  {
    id: "poi_sitabuldi_interchange",
    name: "Sitabuldi Interchange Metro Station",
    category: "Transit",
    subtitle: "Connecting Blue Line & Orange Line",
    lat: 21.1414,
    lon: 79.0825,
    keywords: ["sitabuldi", "interchange", "metro", "station", "blue", "orange", "junction"],
  },
  {
    id: "poi_nagpur_junction",
    name: "Nagpur Railway Station (Main Junction)",
    category: "Transit",
    subtitle: "Station Road, Central Nagpur",
    lat: 21.1528,
    lon: 79.0886,
    keywords: ["nagpur", "railway", "station", "junction", "train", "central"],
  },
  {
    id: "poi_airport",
    name: "Dr. Babasaheb Ambedkar International Airport",
    category: "Transit",
    subtitle: "Sonegaon, Wardha Road, Nagpur",
    lat: 21.0864,
    lon: 79.0638,
    keywords: ["airport", "international", "flight", "terminal", "sonegaon", "wardha", "road"],
  },
  {
    id: "poi_ganeshpeth_bus_stand",
    name: "Ganeshpeth Central Bus Stand (MSRTC ST Stand)",
    category: "Transit",
    subtitle: "Ganeshpeth Colony, Nagpur",
    lat: 21.1415,
    lon: 79.0965,
    keywords: ["ganeshpeth", "bus", "stand", "msrtc", "st", "intercity"],
  },
  {
    id: "poi_mor_bhavan",
    name: "Mor Bhavan City Bus Stand",
    category: "Transit",
    subtitle: "Sitabuldi, Nagpur",
    lat: 21.1435,
    lon: 79.0795,
    keywords: ["mor", "bhavan", "city", "bus", "stand", "sitabuldi", "aapli"],
  },
  {
    id: "poi_ajni_railway",
    name: "Ajni Railway Station",
    category: "Transit",
    subtitle: "Ajni, South-Central Nagpur",
    lat: 21.1235,
    lon: 79.0820,
    keywords: ["ajni", "railway", "station", "train"],
  },

  // ─── MAJOR LOCALITIES & SQUARES ───
  {
    id: "poi_ramdaspeth",
    name: "Ramdaspeth",
    category: "Locality",
    subtitle: "Central commercial & medical hub, Nagpur",
    lat: 21.1375,
    lon: 79.0730,
    keywords: ["ramdaspeth", "central", "hotels", "hospitals"],
  },
  {
    id: "poi_civil_lines",
    name: "Civil Lines",
    category: "Locality",
    subtitle: "Administrative & green district, Nagpur",
    lat: 21.1550,
    lon: 79.0710,
    keywords: ["civil", "lines", "high", "court", "vidhan", "bhavan", "collector"],
  },
  {
    id: "poi_dhantoli",
    name: "Dhantoli",
    category: "Locality",
    subtitle: "Healthcare & residential area, Nagpur",
    lat: 21.1350,
    lon: 79.0830,
    keywords: ["dhantoli", "hospitals", "mehadia"],
  },
  {
    id: "poi_manish_nagar",
    name: "Manish Nagar",
    category: "Locality",
    subtitle: "Somalwada / Wardha Road corridor, Nagpur",
    lat: 21.0890,
    lon: 79.0780,
    keywords: ["manish", "nagar", "somalwada", "wardha", "road", "railway", "crossing"],
  },
  {
    id: "poi_pratap_nagar",
    name: "Pratap Nagar",
    category: "Locality",
    subtitle: "Ring Road / Khamla, South-West Nagpur",
    lat: 21.1180,
    lon: 79.0530,
    keywords: ["pratap", "nagar", "square", "ring", "road"],
  },
  {
    id: "poi_trimurti_nagar",
    name: "Trimurti Nagar",
    category: "Locality",
    subtitle: "Near Ring Road, South-West Nagpur",
    lat: 21.1135,
    lon: 79.0430,
    keywords: ["trimurti", "nagar", "ring", "road"],
  },
  {
    id: "poi_it_park",
    name: "Nagpur IT Park",
    category: "Locality",
    subtitle: "Gayatri Nagar, South Ambazari Road, Nagpur",
    lat: 21.1215,
    lon: 79.0475,
    keywords: ["it", "park", "gayatri", "nagar", "tcs", "persistant", "tech"],
  },
  {
    id: "poi_mihan_sez",
    name: "MIHAN SEZ",
    category: "Locality",
    subtitle: "Multi-modal International Cargo Hub, Nagpur",
    lat: 21.0250,
    lon: 79.0410,
    keywords: ["mihan", "sez", "infosys", "tcs", "hcl", "cargo", "hub"],
  },
  {
    id: "poi_pardi",
    name: "Pardi",
    category: "Locality",
    subtitle: "Bhandara Road, East Nagpur",
    lat: 21.1497,
    lon: 79.1578,
    keywords: ["pardi", "bhandara", "road", "east", "nagpur"],
  },
  {
    id: "poi_nandanvan",
    name: "Nandanvan",
    category: "Locality",
    subtitle: "East Nagpur",
    lat: 21.1350,
    lon: 79.1280,
    keywords: ["nandanvan", "kdk", "college", "east", "nagpur"],
  },
  {
    id: "poi_manewada",
    name: "Manewada",
    category: "Locality",
    subtitle: "Ring Road, South Nagpur",
    lat: 21.1010,
    lon: 79.1020,
    keywords: ["manewada", "ring", "road", "south", "nagpur"],
  },
  {
    id: "poi_besa",
    name: "Besa",
    category: "Locality",
    subtitle: "South Nagpur corridor",
    lat: 21.0820,
    lon: 79.0980,
    keywords: ["besa", "pipla", "beltarodi", "south"],
  },
  {
    id: "poi_shankar_nagar",
    name: "Shankar Nagar Square",
    category: "Locality",
    subtitle: "West Nagpur",
    lat: 21.1375,
    lon: 79.0635,
    keywords: ["shankar", "nagar", "square", "whc", "road"],
  },
  {
    id: "poi_law_college_sq",
    name: "Law College Square",
    category: "Locality",
    subtitle: "Amravati Road, West Nagpur",
    lat: 21.1460,
    lon: 79.0620,
    keywords: ["law", "college", "square", "amravati", "road"],
  },
  {
    id: "poi_medical_square",
    name: "Medical Square",
    category: "Locality",
    subtitle: "GMC / Rambagh corridor, Nagpur",
    lat: 21.1315,
    lon: 79.0970,
    keywords: ["medical", "square", "gmc", "vr", "mall"],
  },
  {
    id: "poi_vca_stadium",
    name: "VCA Stadium (Vidarbha Cricket Association)",
    category: "Monument",
    subtitle: "Civil Lines & Jamtha, Nagpur",
    lat: 21.1565,
    lon: 79.0775,
    keywords: ["vca", "stadium", "cricket", "civil", "lines", "jamtha"],
  },
];
